// Mocks generated by Mockito 5.2.0 from annotations
// in owly/test/src/features/task_management/application/category_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:hooks_riverpod/hooks_riverpod.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:owly/src/features/task_management/data/remote_category_repository.dart'
    as _i2;
import 'package:owly/src/features/task_management/domain/task_category.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [RemoteCategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteCategoryRepository extends _i1.Mock
    implements _i2.RemoteCategoryRepository {
  MockRemoteCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.AsyncValue<List<_i5.TaskCategory>>> watchCategories() =>
      (super.noSuchMethod(Invocation.method(#watchCategories, []),
              returnValue:
                  Stream<_i4.AsyncValue<List<_i5.TaskCategory>>>.empty())
          as _i3.Stream<_i4.AsyncValue<List<_i5.TaskCategory>>>);
}
