CREATE TABLE "public"."tasks" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid (),
  "user_id" uuid NOT NULL,
  "title" text NOT NULL,
  "category_id" uuid NOT NULL,
  "completed" boolean NOT NULL DEFAULT FALSE,
  "due_datetime" timestamptz NOT NULL DEFAULT now(),
  "completed_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz,
  "note" text,
  "index_value" integer,
  "category_color" bigint GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("category_id") REFERENCES "public"."categories" ("id") ON UPDATE RESTRICT ON DELETE CASCADE,
  FOREIGN KEY ("category_color", "category_id") REFERENCES "public"."categories" ("color", "id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
COMMENT ON COLUMN "public"."tasks"."category_color" IS E'This is an identity column and db will fill its value based on the color of the category';